package ui.screen;

public enum TelaEnum {
    MENU_PRINCIPAL,
    REGISTRO_EMPRESTIMO,
    REGISTRO_DEVOLUCAO,
    CADASTRAR_LIVRO,
    PESQUISAR_LIVRO,
    CADASTRAR_USUARIO,
    PESQUISAR_USUARIO,
    HISTORICO
}
