package ui.screen;

public enum TelaEnum {
    MENU_PRINCIPAL,
    REGISTRO_DE_EMPRESTIMO,
    REGISTRO_DE_DEVOLUCAO,
    CADASTRAR_LIVRO,
    PESQUISAR_LIVRO,
    CADASTRAR_USUARIO,
    PESQUISAR_USUARIO,
    CONSULTA_EMPRESTADOS,
    CONSULTA_DEVOLVIDOS,
    CONSULTA_POR_LIVRO
}
